### PR TITLE
conntrack: T3290: Delete deprecated gre helper

### PR DESCRIPTION
**Pull request by sever-sever**
Remove deprecated syntax for conntrack gre modules from CLI.

```
root@r5-roll:/home/vyos# sudo modprobe nf_conntrack_proto_gre
modprobe: FATAL: Module nf_conntrack_proto_gre not found in directory /lib/modules/5.10.12-amd64-vyos
root@r5-roll:/home/vyos# sudo modprobe nf_nat_proto_gre
modprobe: FATAL: Module nf_nat_proto_gre not found in directory /lib/modules/5.10.12-amd64-vyos
root@r5-roll:/home/vyos# 
```

/boot
```
root@r5-roll:/home/vyos# grep CONFIG_NF_CT_PROTO_GRE /boot/config-5.10.12-amd64-vyos 
CONFIG_NF_CT_PROTO_GRE=y

```

### CODE REVIEW

**Comment by c-po** [comment]
So we can not simply delete the nodes we must have a config migrator here. The question is, if it would make sense to switch from a build in driver to a loadable module so it acts as before?

**Comment by sever-sever** [comment]
> So we can not simply delete the nodes we must have a config migrator here. The question is, if it would make sense to switch from a build in driver to a loadable module so it acts as before?

Not sure how it will be better.
@dmbaturin @zdc What is your opinion?

**Comment by bstepler** [comment]
`nf_nat_proto_gre` is gone and `nf_conntrack_proto_gre` can't be built as a module anymore. Also, we should remove GRE references from `templates-cfg/system/conntrack/modules/pptp/disable/node.def` here and `scripts/firewall/firewall.init.in` in `vyatta-cfg-firewall`.

**Comment by zdc** [comment]
It seems that GRE was only a part of PPTP helper anyway.
It was removed as a separated module in the https://github.com/torvalds/linux/commit/22fc4c4c9fd60427bcda00878cee94e7622cfa7a

Therefore, the current state should be:
```
CONFIG_NF_CT_PROTO_GRE=y
CONFIG_NF_CONNTRACK_PPTP=m
```

And the references to the `nf_conntrack_proto_gre` must be removed. A proper migration script required too.

**Pull request closed without merging**
